name: 'Custom action with various output'
on:
  - pull_request_target

jobs:
  my_first_job:
    name: My custom job
    runs-on: ubuntu-latest
    steps:
    - name: The first step
      run: |
        echo "hello world"
        echo "::warning::This is a warning"
        echo "::error::This is an error"
        echo "::debug::This is a debug message"
        echo "::group::Look at this group right here"
        echo "It has some output"
        echo "::debug::and some debug strings"
        echo "::warning::and even a warning"
        echo "::endgroup::"
        echo "Goodbye."
    - name: The second step
      run: |
        echo "This step just succeeds."
        exit 0
  my_second_job:
    name: Here's another job
    runs-on: ubuntu-latest
    steps:
    - name: Steppety step
      run: |
        echo "wow, so many groups"
        echo "::group::Here's a group"
        echo "It has some output"
        echo "::endgroup::"
        echo "::group::Here's another group"
        echo "It has some output"
        echo "::endgroup::"
        echo "::group::There's even a third group"
        echo "::warning::This group has a warning"
        echo "::endgroup::"
        echo "Goodbye."
